export const CAIXA_INSERIDO_SUCESSO = 'Caixa inserido com sucesso'
export const CAIXA_FALHA_INSERIR = 'Falha ao inserir caixa'
export const CAIXA_DELETADO_SUCESSO = 'Caixa deletado com sucesso'
export const ACAO_INSERIDO_SUCESSO = 'Ação inserida com sucesso'
export const ACAO_FALHA_INSERIR = 'Falha ao inserir ação'
export const ACAO_DELETADO_SUCESSO = 'Ação deletada com sucesso'